[project]
name = "extract-pdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pdf2image>=1.17.0",
    "pillow>=12.1.0",
    "pymupdf>=1.26.7",
]
